# lib/gen-codex.sh — Codex generation (config.toml, skills, AGENTS.override.md)
# Sourced by agent-sync.sh. Do not execute directly.
#
# HIST-007: Root entry switched from .agent-rules/AGENTS.md (self-built dir,
# discovered via project_doc_fallback_filenames) to root-level
# AGENTS.override.md. Codex's discovery order — AGENTS.override.md →
# AGENTS.md → fallback names — gives `.override.md` highest precedence in
# the same directory, and Cursor's auto-injection only recognizes
# AGENTS.md / CLAUDE.md (not AGENTS.override.md), so the new file becomes
# a Codex-exclusive entry point with zero Cursor overlap.

generate_codex_config() {
    _ensure_dir "$PROJECT_DIR/.codex" "Codex config directory" || return 0

    if [ -e "$PROJECT_DIR/.codex/config.toml" ] && [ ! -f "$PROJECT_DIR/.codex/config.toml" ]; then
        _warn "  SKIP: .codex/config.toml exists and is not a regular file."
        _warn "        Move or delete it, then rerun agent-sync."
        return 0
    fi

    if [ -f "$PROJECT_DIR/.codex/config.toml" ] && [ ! -f "$CODEX_CONFIG_STAMP" ]; then
        _warn "  SKIP: .codex/config.toml exists and is not managed by agent-sync."
        _warn "        To let agent-sync manage it, delete it and re-run."
        return 0
    fi

    # HIST-007: project_doc_fallback_filenames is no longer needed because
    # AGENTS.override.md is in Codex's native discovery list. Only the
    # child_agents_md feature flag survives — it stays opt-in upstream.
    cat > "$PROJECT_DIR/.codex/config.toml" <<'TOML'
# Auto-generated by agent-sync. Do not edit manually.

[features]
# Enables subdirectory AGENTS.{override.,}md walking so Codex picks up
# sub-repo overlays that agent-sync emits as nested AGENTS.override.md
# files (HIST-007). Renamed from hierarchical_agents in openai/codex PR
# #9215 (2026-01-14).
#
# Source of truth (verified 2026-04-21):
#   openai/codex @ main — codex-rs/features/src/lib.rs
#   → Feature::ChildAgentsMd, Stage::UnderDevelopment, default_enabled=false
#
# The flag is still opt-in — agents-md docs describe the flag-on behavior,
# NOT the default. Removing this line breaks sub-repo AGENTS.override.md
# discovery.
child_agents_md = true
TOML

    touch "$CODEX_CONFIG_STAMP"
    echo "  Codex: .codex/config.toml deployed"
}

# Codex reads user-scoped skills from ~/.agents/skills. Keep the CODEX_HOME
# mirror for compatibility with Codex's bundled skill-installer and clients that
# still annotate or scan ~/.codex/skills.
generate_codex_skills() {
    deploy_artifacts "$RULES_HOME/skills" "$GLOBAL_CODEX_SKILLS_DIR" "$CODEX_SKILLS_MANIFEST" "Global Codex Skills"
    deploy_artifacts "$RULES_HOME/skills" "$GLOBAL_AGENTS_SKILLS_DIR" "$AGENTS_SKILLS_MANIFEST" "Global Agents Skills"
}

# Codex subagents (HIST-006, skeleton). Source:
#   $RULES_HOME/subagents/codex/<name>.toml       (core — Codex uses TOML)
#   $RULES_HOME/extras/<bundle>/subagents/codex/<name>.toml  (optional)
# Target: $PROJECT_DIR/.agents/agents/<prefix><name>.toml
#
# Codex's subagent convention is TOML-per-agent under `.agents/agents/`
# (mirroring the `.agents/skills/` discovery pattern). deploy_subagent_files
# handles both md and toml extensions, so a single function covers the
# whole family.
generate_codex_subagents() {
    deploy_subagent_files "$RULES_HOME/subagents/codex" "$PROJECT_DIR/.agents/agents" "$CODEX_SUBAGENTS_MANIFEST" "Codex Subagents"
}

# Internal: assemble the root Codex AGENTS.override.md body directly.
# Root-level Codex instructions are intentionally language-pack-free: keep the
# cross-tool core plus commit-message policy only, and leave language-specific
# rules to per-tool native rule files or subdirectory overlays. HIST-004 removed
# the previous
# "generate_claude → cp CLAUDE.md AGENTS.md → sed swap header" pipeline because
# CLAUDE.md is no longer a produced artifact; the Codex-specific body now has
# its own narrower assembly path.
_build_agents_body() {
    local agents_file="$1"
    echo "<!-- Auto-generated by agent-sync for Codex. Do not edit manually. -->" > "$agents_file"
    echo "" >> "$agents_file"

    local rule_file
    for rule_file in "$RULES_HOME"/core/*.md; do
        [ -f "$rule_file" ] || continue
        cat "$rule_file" >> "$agents_file"
        echo "" >> "$agents_file"
        echo "---" >> "$agents_file"
        echo "" >> "$agents_file"
    done

    rule_file="$RULES_HOME/packs/git.md"
    if [ -f "$rule_file" ]; then
        cat "$rule_file" >> "$agents_file"
        echo "" >> "$agents_file"
        echo "---" >> "$agents_file"
        echo "" >> "$agents_file"
    fi
}

generate_codex() {
    # HIST-007: root-level AGENTS.override.md is the Codex-exclusive entry
    # point (see file header). No self-built directory needed.
    local agents_file="$PROJECT_DIR/AGENTS.override.md"
    _build_agents_body "$agents_file"

    local agents_size
    agents_size=$(wc -c < "$agents_file" | tr -d ' ')
    echo "  Codex: AGENTS.override.md ($agents_size bytes)"
    if [ "$agents_size" -gt 32768 ]; then
        _warn "  WARNING: AGENTS.override.md exceeds 32KiB ($agents_size bytes). Codex may silently truncate!"
    fi
}
