#!/bin/bash
set -euo pipefail

# agent-sync.sh — Sync rules from central repo to project directory
# Usage: agent-sync.sh [project-dir]
#
# Environment:
#   AGENT_RULES_HOME  — path to central rules repo (default: ~/.config/agent-rules)

RULES_HOME="${AGENT_RULES_HOME:-$HOME/.config/agent-rules}"
PROJECT_DIR="${1:-.}"
PROJECT_DIR="$(cd "$PROJECT_DIR" && pwd)"

HASH_FILE="$PROJECT_DIR/.agent-sync-hash"

# --- Validation ---

if [ ! -d "$RULES_HOME" ]; then
    echo "ERROR: Rules repo not found at $RULES_HOME"
    echo "  Set AGENT_RULES_HOME or create the directory."
    exit 1
fi

if [ ! -d "$RULES_HOME/core" ] || [ ! -d "$RULES_HOME/packs" ]; then
    echo "ERROR: Rules repo missing core/ or packs/ directory."
    exit 1
fi

# --- Check if sync is needed ---

CURRENT_HASH=""
if [ -d "$RULES_HOME/.git" ]; then
    CURRENT_HASH="$(git -C "$RULES_HOME" rev-parse HEAD 2>/dev/null || echo "no-git")"
else
    CURRENT_HASH="$(find "$RULES_HOME" -name '*.md' -newer "$HASH_FILE" 2>/dev/null | head -1 || echo "")"
    [ -n "$CURRENT_HASH" ] && CURRENT_HASH="files-changed" || CURRENT_HASH="no-changes"
fi

STORED_HASH=""
if [ -f "$HASH_FILE" ]; then
    STORED_HASH="$(cat "$HASH_FILE")"
fi

CURSOR_EXISTS=false
CLAUDE_EXISTS=false
AGENTS_EXISTS=false
[ -d "$PROJECT_DIR/.cursor/rules" ] && [ "$(ls -A "$PROJECT_DIR/.cursor/rules/" 2>/dev/null)" ] && CURSOR_EXISTS=true
[ -f "$PROJECT_DIR/CLAUDE.md" ] && CLAUDE_EXISTS=true
[ -f "$PROJECT_DIR/AGENTS.md" ] && AGENTS_EXISTS=true

if [ "$CURRENT_HASH" = "$STORED_HASH" ] && $CURSOR_EXISTS && $CLAUDE_EXISTS && $AGENTS_EXISTS; then
    echo "Rules up to date. No sync needed."
    exit 0
fi

echo "Syncing rules from $RULES_HOME → $PROJECT_DIR"

# --- Generate Cursor .mdc files ---

mkdir -p "$PROJECT_DIR/.cursor/rules"

FRONTMATTER_DIR="$RULES_HOME/templates/cursor-frontmatter"

for rule_file in "$RULES_HOME"/core/*.md "$RULES_HOME"/packs/*.md; do
    [ -f "$rule_file" ] || continue
    basename_no_ext="$(basename "$rule_file" .md)"
    # Strip numeric prefix for frontmatter lookup (00-communication → communication)
    lookup_name="$(echo "$basename_no_ext" | sed 's/^[0-9]*-//')"
    target="$PROJECT_DIR/.cursor/rules/${basename_no_ext}.mdc"

    echo "---" > "$target"
    if [ -f "$FRONTMATTER_DIR/${lookup_name}.yaml" ]; then
        cat "$FRONTMATTER_DIR/${lookup_name}.yaml" >> "$target"
    else
        echo "description: ${lookup_name} rules" >> "$target"
        echo "alwaysApply: false" >> "$target"
    fi
    echo "---" >> "$target"
    echo "" >> "$target"
    cat "$rule_file" >> "$target"
done

# Append project overlay to a separate always-apply .mdc
if [ -f "$PROJECT_DIR/.agent-local.md" ]; then
    target="$PROJECT_DIR/.cursor/rules/project-overlay.mdc"
    echo "---" > "$target"
    echo "description: Project-specific rules and constraints" >> "$target"
    echo "alwaysApply: true" >> "$target"
    echo "---" >> "$target"
    echo "" >> "$target"
    cat "$PROJECT_DIR/.agent-local.md" >> "$target"
fi

echo "  Cursor: $(ls "$PROJECT_DIR/.cursor/rules/"*.mdc 2>/dev/null | wc -l | tr -d ' ') .mdc files"

# --- Generate CLAUDE.md ---

CLAUDE_FILE="$PROJECT_DIR/CLAUDE.md"
echo "<!-- Auto-generated by agent-sync. Do not edit manually. -->" > "$CLAUDE_FILE"
echo "" >> "$CLAUDE_FILE"

for rule_file in "$RULES_HOME"/core/*.md; do
    [ -f "$rule_file" ] || continue
    cat "$rule_file" >> "$CLAUDE_FILE"
    echo "" >> "$CLAUDE_FILE"
    echo "---" >> "$CLAUDE_FILE"
    echo "" >> "$CLAUDE_FILE"
done

for rule_file in "$RULES_HOME"/packs/*.md; do
    [ -f "$rule_file" ] || continue
    cat "$rule_file" >> "$CLAUDE_FILE"
    echo "" >> "$CLAUDE_FILE"
    echo "---" >> "$CLAUDE_FILE"
    echo "" >> "$CLAUDE_FILE"
done

if [ -f "$PROJECT_DIR/.agent-local.md" ]; then
    cat "$PROJECT_DIR/.agent-local.md" >> "$CLAUDE_FILE"
    echo "" >> "$CLAUDE_FILE"
fi

echo "  Claude Code: CLAUDE.md ($(wc -c < "$CLAUDE_FILE" | tr -d ' ') bytes)"

# --- Generate AGENTS.md (same content as CLAUDE.md for Codex) ---

cp "$CLAUDE_FILE" "$PROJECT_DIR/AGENTS.md"
sed -i.bak '1s/.*<!-- Auto-generated.*/<!-- Auto-generated by agent-sync for Codex. Do not edit manually. -->/' "$PROJECT_DIR/AGENTS.md" 2>/dev/null || true
rm -f "$PROJECT_DIR/AGENTS.md.bak"

AGENTS_SIZE=$(wc -c < "$PROJECT_DIR/AGENTS.md" | tr -d ' ')
echo "  Codex: AGENTS.md ($AGENTS_SIZE bytes)"

if [ "$AGENTS_SIZE" -gt 32768 ]; then
    echo "  WARNING: AGENTS.md exceeds 32KiB ($AGENTS_SIZE bytes). Codex may silently truncate!"
fi

# --- Sync Markdown Preview CSS (GitHub-style white background) ---

MD_CSS_SOURCE="$RULES_HOME/templates/github-markdown-preview.css"
if [ -f "$MD_CSS_SOURCE" ]; then
    cp "$MD_CSS_SOURCE" "$PROJECT_DIR/.github-markdown-preview.css"
    mkdir -p "$PROJECT_DIR/.vscode"
    # Merge into .vscode/settings.json without overwriting existing settings
    VSCODE_SETTINGS="$PROJECT_DIR/.vscode/settings.json"
    if [ -f "$VSCODE_SETTINGS" ]; then
        if ! grep -q 'markdown.styles' "$VSCODE_SETTINGS"; then
            # Insert markdown.styles before the closing }
            sed -i.bak 's/}$/,\n    "markdown.styles": [".github-markdown-preview.css"]\n}/' "$VSCODE_SETTINGS" 2>/dev/null || true
            rm -f "$VSCODE_SETTINGS.bak"
        fi
    else
        echo '{"markdown.styles":[".github-markdown-preview.css"]}' > "$VSCODE_SETTINGS"
    fi
    echo "  Markdown Preview: GitHub-style CSS synced"
fi

# --- Store sync hash ---

echo "$CURRENT_HASH" > "$HASH_FILE"

echo "Sync complete."
