#!/usr/bin/env bash
set -euo pipefail

# generate-reviewers.sh — Generate model-specific reviewer sub-agent files from template
#
# Model config is read from .cursor/reviewer-models.conf (one spec per line).
# CLI specs override the config file if provided.
#
# Config file format (.cursor/reviewer-models.conf):
#   # Comments start with #
#   model-id:short-name:Display Name
#
# The main reviewer.md (model: inherit) is NOT generated by this script;
# it is distributed by agent-sync from $AGENT_RULES_HOME/agents/reviewer.md.

if [ -t 1 ]; then
    _G='\033[0;32m' _Y='\033[0;33m' _R='\033[0;31m' _N='\033[0m'
else
    _G='' _Y='' _R='' _N=''
fi
_ok()   { printf '%b%s%b\n' "$_G" "$*" "$_N"; }
_warn() { printf '%b%s%b\n' "$_Y" "$*" "$_N"; }
_err()  { printf '%b%s%b\n' "$_R" "$*" "$_N"; }

show_help() {
    cat <<'EOF'
generate-reviewers — Generate model-specific reviewer sub-agent files

USAGE
    generate-reviewers [project-dir]                              Read from .cursor/reviewer-models.conf
    generate-reviewers [project-dir] "model-id:short:Name" [...]  Use CLI specs (ignores conf)
    generate-reviewers --list [project-dir]
    generate-reviewers --clean [project-dir]
    generate-reviewers -h | --help

CONFIG FILE
    .cursor/reviewer-models.conf in the target project directory.
    One model spec per line: model-id:short-name:Display Name
    Lines starting with # and empty lines are ignored.

    Copy the reference template from:
      $AGENT_RULES_HOME/templates/reviewer-models.conf

SUBCOMMANDS
    --list     List currently generated reviewer variants
    --clean    Remove all generated variants (keeps main reviewer.md)

EXAMPLES
    # Using config file (recommended)
    cp $AGENT_RULES_HOME/templates/reviewer-models.conf .cursor/
    vim .cursor/reviewer-models.conf   # uncomment/add models
    generate-reviewers .

    # Using CLI specs (overrides config file)
    generate-reviewers . "kimi-k2.5:kimi:Kimi K2.5" "gpt-5.4-xhigh:gpt54:GPT-5.4"

    generate-reviewers --list .
    generate-reviewers --clean .
EOF
    exit 0
}

RULES_HOME="${AGENT_RULES_HOME:-$HOME/.config/agent-rules}"
TEMPLATE="$RULES_HOME/templates/agents/reviewer-variant.md"

# --- Parse arguments ---

ACTION="generate"
case "${1:-}" in
    -h|--help) show_help ;;
    --list)  ACTION="list";  shift ;;
    --clean) ACTION="clean"; shift ;;
esac

PROJECT_DIR="${1:-.}"
PROJECT_DIR="$(cd "$PROJECT_DIR" && pwd)"
shift 2>/dev/null || true

AGENTS_DIR="$PROJECT_DIR/.cursor/agents"
MANIFEST="$AGENTS_DIR/.generated-reviewers-manifest"
CONF_FILE="$PROJECT_DIR/.cursor/reviewer-models.conf"

# --- Read config file ---

read_conf_specs() {
    local specs=()
    if [ ! -f "$CONF_FILE" ]; then
        return 0
    fi
    while IFS= read -r line; do
        # Skip comments and empty lines
        line="$(printf '%s' "$line" | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')"
        [[ -z "$line" || "$line" == \#* ]] && continue
        specs+=("$line")
    done < "$CONF_FILE"
    if [ ${#specs[@]} -gt 0 ]; then
        printf '%s\n' "${specs[@]}"
    fi
}

# --- List ---

do_list() {
    if [ ! -f "$MANIFEST" ]; then
        echo "No generated reviewer variants found in $PROJECT_DIR"
        if [ -f "$CONF_FILE" ]; then
            echo "Config file exists at $CONF_FILE — run 'generate-reviewers .' to generate."
        fi
        exit 0
    fi
    echo "Generated reviewer variants in $PROJECT_DIR:"
    while IFS= read -r entry; do
        [ -z "$entry" ] && continue
        local file model display
        file="$(echo "$entry" | cut -d'|' -f1)"
        model="$(echo "$entry" | cut -d'|' -f2)"
        display="$(echo "$entry" | cut -d'|' -f3)"
        if [ -f "$AGENTS_DIR/$file" ]; then
            printf '  %-30s  model: %-25s  (%s)\n' "$file" "$model" "$display"
        else
            printf '  %-30s  [MISSING]\n' "$file"
        fi
    done < "$MANIFEST"
}

# --- Clean ---

do_clean() {
    if [ ! -f "$MANIFEST" ]; then
        echo "No generated reviewer variants to clean."
        exit 0
    fi
    local count=0
    while IFS= read -r entry; do
        [ -z "$entry" ] && continue
        local file
        file="$(echo "$entry" | cut -d'|' -f1)"
        if [ -f "$AGENTS_DIR/$file" ]; then
            rm -f "$AGENTS_DIR/$file"
            echo "  Removed $file"
            count=$((count + 1))
        fi
    done < "$MANIFEST"
    rm -f "$MANIFEST"
    _ok "Cleaned $count reviewer variant(s)."
}

# --- Generate ---

do_generate() {
    if [ ! -f "$TEMPLATE" ]; then
        _err "ERROR: Template not found at $TEMPLATE"
        _err "  Ensure AGENT_RULES_HOME is set correctly (current: $RULES_HOME)"
        exit 1
    fi

    # Resolve specs: CLI args take priority, then config file
    local specs=()
    if [ $# -gt 0 ]; then
        specs=("$@")
    else
        while IFS= read -r spec; do
            specs+=("$spec")
        done < <(read_conf_specs)
    fi

    if [ ${#specs[@]} -eq 0 ]; then
        if [ -f "$CONF_FILE" ]; then
            _warn "Config file $CONF_FILE exists but contains no active model specs."
            _warn "  Uncomment or add lines in model-id:short-name:Display Name format."
        else
            echo "No config file at $CONF_FILE and no CLI specs provided. Nothing to generate."
        fi
        # Clean up stale variants if config was emptied
        if [ -f "$MANIFEST" ]; then
            do_clean
        fi
        return 0
    fi

    mkdir -p "$AGENTS_DIR"
    local manifest_new="${MANIFEST}.new"
    : > "$manifest_new"
    local count=0

    for spec in "${specs[@]}"; do
        local model_id short_name display_name
        model_id="$(printf '%s' "$spec" | cut -d':' -f1)"
        short_name="$(printf '%s' "$spec" | cut -d':' -f2)"
        # Display name is everything after the second colon
        display_name="$(printf '%s' "$spec" | cut -d':' -f3-)"

        if [ -z "$model_id" ] || [ -z "$short_name" ] || [ -z "$display_name" ]; then
            _warn "  SKIP: invalid spec '$spec' — expected 'model-id:short-name:Display Name'"
            continue
        fi

        # Validate short_name: only alphanumeric, hyphens, underscores allowed
        if [[ ! "$short_name" =~ ^[a-zA-Z0-9_-]+$ ]]; then
            _warn "  SKIP: invalid short_name '$short_name' — only [a-zA-Z0-9_-] allowed"
            continue
        fi

        local target="$AGENTS_DIR/reviewer-${short_name}.md"
        # Use awk for safe template expansion (no sed delimiter/metacharacter issues)
        awk -v mid="$model_id" -v sn="$short_name" -v dn="$display_name" \
            '{gsub(/\{\{MODEL_ID\}\}/, mid); gsub(/\{\{SHORT_NAME\}\}/, sn); gsub(/\{\{DISPLAY_NAME\}\}/, dn); print}' \
            "$TEMPLATE" > "$target"

        printf '%s\n' "reviewer-${short_name}.md|${model_id}|${display_name}" >> "$manifest_new"
        printf '  Generated reviewer-%s.md  (model: %s)\n' "$short_name" "$model_id"
        count=$((count + 1))
    done

    # Remove variants from previous generation that are no longer in the spec list
    if [ -f "$MANIFEST" ]; then
        while IFS= read -r old_entry; do
            [ -z "$old_entry" ] && continue
            local old_file
            old_file="$(printf '%s' "$old_entry" | cut -d'|' -f1)"
            if ! grep -Fq "${old_file}|" "$manifest_new" 2>/dev/null; then
                rm -f "$AGENTS_DIR/$old_file"
                printf '  Removed stale: %s\n' "$old_file"
            fi
        done < "$MANIFEST"
    fi

    mv "$manifest_new" "$MANIFEST"
    _ok "Generated $count reviewer variant(s) in $AGENTS_DIR/"
}

# --- Main dispatch ---

case "$ACTION" in
    list)     do_list ;;
    clean)    do_clean ;;
    generate) do_generate "$@" ;;
esac
